version: '3'

services:
  dj:
    container_name: dj
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./management:/app
    ports:
      - "1604:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: product-management-db
    restart: always
    env_file:
      - .postgres.env
    ports:
      - "1605:5432"

  adminer:
    image: adminer
    container_name: product-management-adminer
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.adminer
    ports:
      - "1608:8080"

volumes:
  dev-db-data:
